#!/usr/bin/env python
#
# (c)2015 Aaron Kondziela <aaron@aaronkondziela.com>
# Distributed under the MIT License
#

import RPi.GPIO as GPIO
import time

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

GPIO.setup(19, GPIO.OUT, initial=0)

GPIO.output(19, 1)

