#!/usr/bin/env bash
#
# (c)2015 Aaron Kondziela <aaron@aaronkondziela.com>
# Distributed under the MIT License
#

FILE=/home/pi/sunrise-sunset.data

# How many seconds window for check
# Should be set on context of crontab frequency
WINDOW=60

# Yahoo gives it to you in local time, so twiddle TZ for date command
export TZ="America/New_York"

SUNRISE=`date --date="$(cat $FILE | awk -F\" '{print $2}')" +%s`
SUNSET=`date --date="$(cat $FILE | awk -F\" '{print $4}')" +%s`

# Reset TZ back to a nice sane UTC
export TZ=""

NOW=`date +%s`

if (( $NOW - $SUNSET > 0 && $NOW - $SUNSET < $WINDOW )) ; then
	echo Sun did just set within $WINDOW seconds
	exit 0
else
	echo Sun did not just set within $WINDOW seconds
	exit 1
fi
